### ISSUE TITLE
Error while trying to run inference.py

### ISSUE THREAD

**Issue by joeprice20** [AlonShoshan10/dynamic_net#4]
Hi, I've been having lots of trouble to get this program to work and I keep getting many errors, is there any chance you could provide a more detailed explanation of how to get the program running and what versions of python and dependencies are being used as I think that's what's causing lots of the issues. 

`(image) D:\dynamic_net-master\dynamic_style_transfer>python inference.py --network_name=mosaic --use_saved_config=False --set_net_version=normal
Traceback (most recent call last):
  File "inference.py", line 2, in <module>
    from models.inference_model import InferenceModel
  File "D:\dynamic_net-master\dynamic_style_transfer\models\inference_model.py", line 1, in <module>
    from models.base_model import BaseModel
  File "D:\dynamic_net-master\dynamic_style_transfer\models\base_model.py", line 1, in <module>
    import torch
  File "D:\anaconda\envs\image\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: The operating system cannot run %1.`

This is one of the error codes I have got

**Comment by AlonShoshan10** [comment]
Hi, I am using a conda env with python 3.6.
Here are all the packages that are installed in the env I used (I hope it helps you):

*using conda list
Name                    Version                   Build  Channel
absl-py                   0.5.0                    pypi_0    pypi
asn1crypto                0.24.0                     py_1    conda-forge
astor                     0.7.1                    pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
blas                      1.0                         mkl    anaconda
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2019.11.27                    0  
cairo                     1.14.12              h77bcde2_0  
certifi                   2019.11.28               py36_0  
cffi                      1.11.5           py36h9745a5d_0  
chardet                   3.0.4                      py_1    conda-forge
cloudpickle               0.5.3                    py36_0    anaconda
cryptography              2.2.1            py36hdffb7b8_1    conda-forge
cudatoolkit               8.0                           3    https://repo.continuum.io/pkgs/free
dbus                      1.13.0               h3a4f0e9_0    conda-forge
dominate                  2.3.1                    py36_0    conda-forge
expat                     2.2.5                         0    conda-forge
ffmpeg                    3.2.4                         3    conda-forge
fontconfig                2.12.6               h49f89f6_0  
freetype                  2.8                  hab7d2ae_1  
gast                      0.2.0                    pypi_0    pypi
giflib                    5.1.4                h470a237_0    conda-forge
glib                      2.53.6               h5d9569c_2  
graphite2                 1.3.11               hfc679d8_0    conda-forge
grpcio                    1.15.0                   pypi_0    pypi
gst-plugins-base          1.12.4               h33fb286_0  
gstreamer                 1.12.4               hb53b477_0  
h5py                      2.8.0                    pypi_0    pypi
harfbuzz                  1.7.6                hc5b324e_0  
hdf5                      1.10.2               hba1933b_1    anaconda
icu                       58.2                          0    conda-forge
idna                      2.7                        py_1    conda-forge
intel-openmp              2018.0.0                      8  
ipython                   7.2.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jasper                    1.900.1                       4    conda-forge
jedi                      0.13.2                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
keras-applications        1.0.6                    pypi_0    pypi
keras-preprocessing       1.0.5                    pypi_0    pypi
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1    https://repo.continuum.io/pkgs/free
libgfortran-ng            7.2.0                hdf63c60_3  
libiconv                  1.15                          0    conda-forge
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.34               hb9fc6fc_0  
libsodium                 1.0.16                        0    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                he85c1e1_1  
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.8                         0    conda-forge
libxslt                   1.1.32                        0    conda-forge
markdown                  3.0.1                    pypi_0    pypi
mkl                       2018.0.2                      1  
ncurses                   6.1                  hf484d3e_0  
ninja                     1.8.2            py36h6bb024c_1  
numpy                     1.14.2           py36hdbf6ddf_0  
olefile                   0.45.1                   py36_0  
openblas                  0.2.20                        8    conda-forge
opencv                    3.4.1            py36h6fd60c2_1    anaconda
opencv-python             3.4.3.18                 pypi_0    pypi
openssl                   1.0.2p               h14c3975_0  
parso                     0.3.3                    pypi_0    pypi
pcre                      8.41                          1    conda-forge
pexpect                   4.6.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    5.1.0            py36h3deb7b8_0  
pip                       19.0.1                   pypi_0    pypi
pixman                    0.34.0                        2    conda-forge
prompt-toolkit            2.0.8                    pypi_0    pypi
protobuf                  3.6.1                    pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pycparser                 2.18             py36hf9f622e_1  
pygments                  2.3.1                    pypi_0    pypi
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.6.0            py36h0386399_5    anaconda
pyside2                   5.6.0a1                  py36_2    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.5                hc3d631a_2  
python-lmdb               0.92                     py36_0    conda-forge
pytorch                   0.4.0           py36_cuda8.0.61_cudnn7.1.2_1    pytorch
pyzmq                     17.0.0                   py36_4    conda-forge
qt                        5.6.2               hd25b39d_14  
readline                  7.0                  ha6073c6_4  
requests                  2.19.1                     py_1    conda-forge
scikit-learn              0.19.1           py36h7aa7ec6_0    anaconda
scipy                     1.1.0            py36hfc37229_0    anaconda
setuptools                39.1.0                   pypi_0    pypi
sip                       4.18.1           py36h51ed4ed_2    anaconda
six                       1.11.0           py36h372c433_1  
sqlite                    3.23.1               he433501_0  
tensorboard               1.11.0                   pypi_0    pypi
tensorboard-logger        0.1.0                    pypi_0    pypi
tensorflow                1.11.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.7                hc745277_3  
torchfile                 0.1.0                      py_0    conda-forge
torchvision               0.2.1                    py36_1    pytorch
tornado                   5.0.2                    py36_0    conda-forge
tqdm                      4.23.4                   py36_0  
traitlets                 4.3.2                    pypi_0    pypi
urllib3                   1.23                     py36_0    conda-forge
visdom                    0.1.8.3                       0    conda-forge
wcwidth                   0.1.7                    pypi_0    pypi
websocket-client          0.48.0                     py_0    conda-forge
werkzeug                  0.14.1                   pypi_0    pypi
wheel                     0.31.1                   py36_0  
x264                      20131218                      0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.5                hfc679d8_3    conda-forge
zlib                      1.2.11               ha838bed_2
